const suggestions = [
  'Who is my celebrity crush?',
  'Am I scared or ok with weight gain?',
  'Do I have any allergies?',
  'What’s my favorite sandwich?',
  'Do I know how to cook?',
  'What is my favorite meal of the day?',
  'What is my favorite time of the day?',
  'How old was I when I had my first relationship?',
  'Am I shy or outgoing?',
  'Do I like to laugh?',
  'Am I irritable?',
  'Where was I born?',
  'How old am I?',
  'How tall am I?',
  'What’s my favorite food?',
  'Where’s my favorite vacation spot?',
  'What’s my biggest fear?',
  'What’s my zodiac sign?',
  'What’s my mom’s name?',
  'What’s my dad’s name?',
  'Do I have any brothers or sisters?',
  'What do my parents do for living?',
  'Who is my favorite artist?',
  'Are my parents divorced?',
  'What kind of kid was I?',
  'Have I ever been in any serious trouble?',
  'What’s my favorite movie?',
  'Do I have any pets?',
  'Who’s my oldest friend?',
  'Who’s my favorite family member?',
  'Who is my idol?',
  'Do I play any instruments? if Yes, Which?',
  'What countries have I been too?',
  'Where did I go to school?',
  'Have I ever travelled in first class?',
  'If I could own anything what would it be?',
  'What is my favorite beverage or cocktail?',
  'Would I rather have pizza or cheeseburgers?',
  'Do I like spicy food?',
  'What makes me happy?',
  'What makes me sad?',
  'What makes me angry?',
  'What’s the best gift you have ever given?',
  'What is the best gift you have ever received?',
  'Have I ever had any serious relationships before?',
  'What would make me jealous?',
  'What is my favorite outfit?',
  'What are my favorite type of shoes?',
  'Do I like the rain?',
  'Do I like the snow?',
  'Where do I work?',
  'Do I like my job?',
  'If I could work anywhere where would that be?',
  'What was my first job?',
  'Have I ever quit?',
  'Have I ever been fired?',
  'Do I like cats or dogs?',
  'What’s my favorite color?',
  'Did I ever play any sports?',
  'What’s my favorite team?',
  'Who’s my favorite band?',
  'What’s my favorite type of music?',
  'What’s my least favorite type of music?',
  'What’s my favorite tv show?',
  'What’s one part of pop culture I hate?',
  'What’s one fad I fell victim to',
  'Am I organized?',
  'What makes me nervous?',
  'What are my hidden talents?',
  'Do I have any hobbies?',
  'Who has made the most difference in my life?',
  'Have I ever been in trouble with the law?',
  'Have I ever had a sexual experience with a member of the same sex?',
  'What do I think about social media?',
  'Have I ever won any awards?',
  'What is my view on politics?',
  'What are my political views?',
  'What is one thing I hate?',
  'What is one thing I love?',
  'Am I religious?',
  'Do I believe in life after death?',
  'Have I ever been in a fight?',
  'What’s the worst experience of my life?',
  'What is the best experience of my life?',
  'Has a song ever made me cry? If so, which one?',
  'Has a movie ever made me cry? If so, which one?',
  'My biggest fear?',
  'Am I an emotional person?',
  'What’s the one food I could never get sick of eating?',
  'What’s my favorite dessert?',
  'What’s the first thing on my bucket list?',
  'Where is the one place I would move to?',
  'Who is my closest family member?',
  'Would I rather be by the lake or the ocean?',
  'Would I rather be by water or in the mountains?',
  'What are three things I would bring to a deserted island?',
  'What’s my all time favorite TV show?',
  'What’s my all time favorite movie?',
  'What’s one thing I would change in my life?',
  'What’s one thing about me I would change if I could?',
  'What would be my dream job?',
  'Who was my hero as a child?',
  'What was my favorite childhood TV show?',
  'What language would I most like to be fluent in?',
  'What’s something that cheers me up when I’m sad?',
  'What is something I can’t sleep without?',
  'Where am I most comfortable?',
  'What’s my favorite romantic gesture?',
  'What’s my favorite book?',
  'What spice or herb can I not stand?',
  'What’s my preferred brand of chocolate?',
  'What do I like most about you?',
  'When’s my birthday?',
  'What is my most favorite pet?',
  'What flavor of ice cream is my favorite?',
  'What am I most proud of?',
  'Where is the one foreign country I want to visit most?',
  'Would I rather go to a play or a concert?',
  'Who’s someone that inspires me most?',
  'What is my favorite childhood memory?',
  'What do I want to accomplish most before I die?',
  'What’s my favorite clothing store?',
  'Am I a cat or a dog person?',
  'What’s something that fascinates me no matter what?',
  'What would I love to take classes in?',
  'What’s my guilty-pleasure snack?',
  'What’s my go-to Netflix show/movie?',

];
export default suggestions;
